name: Test Action

on:
  workflow_dispatch:
    inputs:
      tag_name:
        type: string
  push:
    branches:
      - main
    paths:
      - test/version.py

jobs:
  release:
    needs: build-wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set tag name
        id: set_tag_name
        run: |
          if [ -z "${{ inputs.tag_name }}" ]; then
            TAG_NAME="v$(cat test/version.py | cut -d'"' -f2)"
            echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          else
            echo "tag_name={{ inputs.tag_name }} >> $GITHUB_OUTPUT
          fi
      
      - name: Echo output
        run: |
          echo "${{ steps.set_tag_name.outputs.tag_name }}"
